// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.Data;

#nullable disable

namespace Portal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260609162842_AddStudentChallenges")]
    partial class AddStudentChallenges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Portal.Models.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLinkCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("access_link_code");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_challenges");

                    b.HasIndex("AccessLinkCode")
                        .IsUnique()
                        .HasDatabaseName("ix_challenges_access_link_code");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_challenges_class_id");

                    b.HasIndex("TeacherId", "ClassId", "DeletedAt")
                        .HasDatabaseName("ix_challenges_teacher_id_class_id_deleted_at");

                    b.ToTable("challenges", (string)null);
                });

            modelBuilder.Entity("Portal.Models.ClassEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_class_enrollments");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_class_enrollments_student_id");

                    b.HasIndex("ClassId", "StudentId", "DeletedAt")
                        .HasDatabaseName("ix_class_enrollments_class_id_student_id_deleted_at");

                    b.ToTable("class_enrollments", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EntryMonth")
                        .HasColumnType("int")
                        .HasColumnName("entry_month");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("entry_type");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("recurrence");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int")
                        .HasColumnName("scenario_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.HasIndex("ScenarioId", "DeletedAt")
                        .HasDatabaseName("ix_entries_scenario_id_deleted_at");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int")
                        .HasColumnName("scenario_id");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("target_value");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int")
                        .HasColumnName("term_months");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_objectives");

                    b.HasIndex("ScenarioId", "DeletedAt")
                        .HasDatabaseName("ix_objectives_scenario_id_deleted_at");

                    b.ToTable("objectives", (string)null);
                });

            modelBuilder.Entity("Portal.Models.QuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<int>("SelectedOptionId")
                        .HasColumnType("int")
                        .HasColumnName("selected_option_id");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quiz_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_quiz_answers_question_id");

                    b.HasIndex("SelectedOptionId")
                        .HasDatabaseName("ix_quiz_answers_selected_option_id");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_quiz_answers_submission_id");

                    b.ToTable("quiz_answers", (string)null);
                });

            modelBuilder.Entity("Portal.Models.QuizOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_correct");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quiz_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_quiz_options_question_id");

                    b.ToTable("quiz_options", (string)null);
                });

            modelBuilder.Entity("Portal.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int")
                        .HasColumnName("challenge_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quiz_questions");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_quiz_questions_challenge_id");

                    b.ToTable("quiz_questions", (string)null);
                });

            modelBuilder.Entity("Portal.Models.QuizSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int")
                        .HasColumnName("challenge_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quiz_submissions");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_quiz_submissions_challenge_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_quiz_submissions_student_id");

                    b.ToTable("quiz_submissions", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("int")
                        .HasColumnName("challenge_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("family_name");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("initial_balance");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scenarios");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_scenarios_challenge_id");

                    b.HasIndex("StudentId", "ChallengeId", "DeletedAt")
                        .HasDatabaseName("ix_scenarios_student_id_challenge_id_deleted_at");

                    b.ToTable("scenarios", (string)null);
                });

            modelBuilder.Entity("Portal.Models.ScenarioMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("monthly_income");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int")
                        .HasColumnName("scenario_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scenario_members");

                    b.HasIndex("ScenarioId", "DeletedAt")
                        .HasDatabaseName("ix_scenario_members_scenario_id_deleted_at");

                    b.ToTable("scenario_members", (string)null);
                });

            modelBuilder.Entity("Portal.Models.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("MembershipCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("membership_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("MembershipCode")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_membership_code");

                    b.HasIndex("TeacherId", "DeletedAt")
                        .HasDatabaseName("ix_classes_teacher_id_deleted_at");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("Portal.Models.StudentChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int")
                        .HasColumnName("challenge_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enrolled_at");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_student_challenges");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_student_challenges_challenge_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_challenges_student_id");

                    b.ToTable("student_challenges", (string)null);
                });

            modelBuilder.Entity("Portal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("gender_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserStatusId")
                        .HasColumnType("int")
                        .HasColumnName("user_status_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("UserStatusId")
                        .HasDatabaseName("ix_users_user_status_id");

                    b.HasIndex("RoleId", "UserStatusId", "DeletedAt")
                        .HasDatabaseName("ix_users_role_id_user_status_id_deleted_at");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Portal.Models.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_statuses");

                    b.ToTable("user_statuses", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Challenge", b =>
                {
                    b.HasOne("Portal.Models.SchoolClass", "Class")
                        .WithMany("Challenges")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("fk_challenges_classes_class_id");

                    b.HasOne("Portal.Models.User", "Teacher")
                        .WithMany("CreatedChallenges")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_challenges_users_teacher_id");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Portal.Models.ClassEnrollment", b =>
                {
                    b.HasOne("Portal.Models.SchoolClass", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_enrollments_classes_class_id");

                    b.HasOne("Portal.Models.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_enrollments_users_student_id");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Portal.Models.Entry", b =>
                {
                    b.HasOne("Portal.Models.Scenario", "Scenario")
                        .WithMany("Entries")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entries_scenarios_scenario_id");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("Portal.Models.Objective", b =>
                {
                    b.HasOne("Portal.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_objectives_scenarios_scenario_id");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("Portal.Models.QuizAnswer", b =>
                {
                    b.HasOne("Portal.Models.QuizQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_answers_quiz_questions_question_id");

                    b.HasOne("Portal.Models.QuizOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_answers_quiz_options_selected_option_id");

                    b.HasOne("Portal.Models.QuizSubmission", "Submission")
                        .WithMany("Answers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_answers_quiz_submissions_submission_id");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Portal.Models.QuizOption", b =>
                {
                    b.HasOne("Portal.Models.QuizQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_options_quiz_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Portal.Models.QuizQuestion", b =>
                {
                    b.HasOne("Portal.Models.Challenge", "Challenge")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_questions_challenges_challenge_id");

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("Portal.Models.QuizSubmission", b =>
                {
                    b.HasOne("Portal.Models.Challenge", "Challenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_submissions_challenges_challenge_id");

                    b.HasOne("Portal.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_submissions_users_student_id");

                    b.Navigation("Challenge");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Portal.Models.Scenario", b =>
                {
                    b.HasOne("Portal.Models.Challenge", "Challenge")
                        .WithMany("Scenarios")
                        .HasForeignKey("ChallengeId")
                        .HasConstraintName("fk_scenarios_challenges_challenge_id");

                    b.HasOne("Portal.Models.User", "Student")
                        .WithMany("Scenarios")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scenarios_users_student_id");

                    b.Navigation("Challenge");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Portal.Models.ScenarioMember", b =>
                {
                    b.HasOne("Portal.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scenario_members_scenarios_scenario_id");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("Portal.Models.SchoolClass", b =>
                {
                    b.HasOne("Portal.Models.User", "Teacher")
                        .WithMany("TaughtClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_users_teacher_id");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Portal.Models.StudentChallenge", b =>
                {
                    b.HasOne("Portal.Models.Challenge", "Challenge")
                        .WithMany("StudentChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_challenges_challenges_challenge_id");

                    b.HasOne("Portal.Models.User", "Student")
                        .WithMany("StudentChallenges")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_challenges_users_student_id");

                    b.Navigation("Challenge");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Portal.Models.User", b =>
                {
                    b.HasOne("Portal.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.HasOne("Portal.Models.UserStatus", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("UserStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_user_statuses_user_status_id");

                    b.Navigation("Role");

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("Portal.Models.Challenge", b =>
                {
                    b.Navigation("QuizQuestions");

                    b.Navigation("Scenarios");

                    b.Navigation("StudentChallenges");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Portal.Models.QuizQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Portal.Models.QuizSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Portal.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Portal.Models.Scenario", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Portal.Models.SchoolClass", b =>
                {
                    b.Navigation("Challenges");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Portal.Models.User", b =>
                {
                    b.Navigation("CreatedChallenges");

                    b.Navigation("Enrollments");

                    b.Navigation("Scenarios");

                    b.Navigation("StudentChallenges");

                    b.Navigation("TaughtClasses");
                });

            modelBuilder.Entity("Portal.Models.UserStatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
