// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.Data;

#nullable disable

namespace Portal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612142230_AddChallengeSubmissions")]
    partial class AddChallengeSubmissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Portal.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_email");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("ix_audit_logs_user_id_timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLinkCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("access_link_code");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_challenges");

                    b.HasIndex("AccessLinkCode")
                        .IsUnique()
                        .HasDatabaseName("ix_challenges_access_link_code");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_challenges_class_id");

                    b.HasIndex("TeacherId", "ClassId", "DeletedAt")
                        .HasDatabaseName("ix_challenges_teacher_id_class_id_deleted_at");

                    b.ToTable("challenges", (string)null);
                });

            modelBuilder.Entity("Portal.Models.ChallengeSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int")
                        .HasColumnName("challenge_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("MultipleChoiceAnswer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("multiple_choice_answer");

                    b.Property<string>("SimpleQuestionAnswer")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("simple_question_answer");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<bool>("TrueFalseAnswer")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("true_false_answer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_challenge_submissions");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_challenge_submissions_challenge_id");

                    b.HasIndex("StudentId", "ChallengeId", "DeletedAt")
                        .HasDatabaseName("ix_challenge_submissions_student_id_challenge_id_deleted_at");

                    b.ToTable("challenge_submissions", (string)null);
                });

            modelBuilder.Entity("Portal.Models.ClassEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_class_enrollments");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_class_enrollments_student_id");

                    b.HasIndex("ClassId", "StudentId", "DeletedAt")
                        .HasDatabaseName("ix_class_enrollments_class_id_student_id_deleted_at");

                    b.ToTable("class_enrollments", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EntryMonth")
                        .HasColumnType("int")
                        .HasColumnName("entry_month");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("entry_type");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("recurrence");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int")
                        .HasColumnName("scenario_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.HasIndex("ScenarioId", "DeletedAt")
                        .HasDatabaseName("ix_entries_scenario_id_deleted_at");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int")
                        .HasColumnName("scenario_id");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("target_value");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int")
                        .HasColumnName("term_months");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_objectives");

                    b.HasIndex("ScenarioId", "DeletedAt")
                        .HasDatabaseName("ix_objectives_scenario_id_deleted_at");

                    b.ToTable("objectives", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("int")
                        .HasColumnName("challenge_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("family_name");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("initial_balance");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scenarios");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_scenarios_challenge_id");

                    b.HasIndex("StudentId", "ChallengeId", "DeletedAt")
                        .HasDatabaseName("ix_scenarios_student_id_challenge_id_deleted_at");

                    b.ToTable("scenarios", (string)null);
                });

            modelBuilder.Entity("Portal.Models.ScenarioMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("monthly_income");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int")
                        .HasColumnName("scenario_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scenario_members");

                    b.HasIndex("ScenarioId", "DeletedAt")
                        .HasDatabaseName("ix_scenario_members_scenario_id_deleted_at");

                    b.ToTable("scenario_members", (string)null);
                });

            modelBuilder.Entity("Portal.Models.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("MembershipCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("membership_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("MembershipCode")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_membership_code");

                    b.HasIndex("TeacherId", "DeletedAt")
                        .HasDatabaseName("ix_classes_teacher_id_deleted_at");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("Portal.Models.SimulationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<double?>("MonthlyCommission")
                        .HasColumnType("double")
                        .HasColumnName("monthly_commission");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("parameters_json");

                    b.Property<string>("Periodicity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("periodicity");

                    b.Property<double>("Principal")
                        .HasColumnType("double")
                        .HasColumnName("principal");

                    b.Property<double>("RatePercentage")
                        .HasColumnType("double")
                        .HasColumnName("rate_percentage");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("result_json");

                    b.Property<string>("SimulationMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("simulation_mode");

                    b.Property<double>("Time")
                        .HasColumnType("double")
                        .HasColumnName("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_simulation_histories");

                    b.HasIndex("UserId", "DeletedAt")
                        .HasDatabaseName("ix_simulation_histories_user_id_deleted_at");

                    b.ToTable("simulation_histories", (string)null);
                });

            modelBuilder.Entity("Portal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("gender_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserStatusId")
                        .HasColumnType("int")
                        .HasColumnName("user_status_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("UserStatusId")
                        .HasDatabaseName("ix_users_user_status_id");

                    b.HasIndex("RoleId", "UserStatusId", "DeletedAt")
                        .HasDatabaseName("ix_users_role_id_user_status_id_deleted_at");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Portal.Models.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_statuses");

                    b.ToTable("user_statuses", (string)null);
                });

            modelBuilder.Entity("Portal.Models.Challenge", b =>
                {
                    b.HasOne("Portal.Models.SchoolClass", "Class")
                        .WithMany("Challenges")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("fk_challenges_classes_class_id");

                    b.HasOne("Portal.Models.User", "Teacher")
                        .WithMany("CreatedChallenges")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_challenges_users_teacher_id");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Portal.Models.ChallengeSubmission", b =>
                {
                    b.HasOne("Portal.Models.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_submissions_challenges_challenge_id");

                    b.HasOne("Portal.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_submissions_users_student_id");

                    b.Navigation("Challenge");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Portal.Models.ClassEnrollment", b =>
                {
                    b.HasOne("Portal.Models.SchoolClass", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_enrollments_classes_class_id");

                    b.HasOne("Portal.Models.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_enrollments_users_student_id");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Portal.Models.Entry", b =>
                {
                    b.HasOne("Portal.Models.Scenario", "Scenario")
                        .WithMany("Entries")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entries_scenarios_scenario_id");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("Portal.Models.Objective", b =>
                {
                    b.HasOne("Portal.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_objectives_scenarios_scenario_id");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("Portal.Models.Scenario", b =>
                {
                    b.HasOne("Portal.Models.Challenge", "Challenge")
                        .WithMany("Scenarios")
                        .HasForeignKey("ChallengeId")
                        .HasConstraintName("fk_scenarios_challenges_challenge_id");

                    b.HasOne("Portal.Models.User", "Student")
                        .WithMany("Scenarios")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scenarios_users_student_id");

                    b.Navigation("Challenge");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Portal.Models.ScenarioMember", b =>
                {
                    b.HasOne("Portal.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scenario_members_scenarios_scenario_id");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("Portal.Models.SchoolClass", b =>
                {
                    b.HasOne("Portal.Models.User", "Teacher")
                        .WithMany("TaughtClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_users_teacher_id");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Portal.Models.SimulationHistory", b =>
                {
                    b.HasOne("Portal.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_simulation_histories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Portal.Models.User", b =>
                {
                    b.HasOne("Portal.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.HasOne("Portal.Models.UserStatus", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("UserStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_user_statuses_user_status_id");

                    b.Navigation("Role");

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("Portal.Models.Challenge", b =>
                {
                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("Portal.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Portal.Models.Scenario", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Portal.Models.SchoolClass", b =>
                {
                    b.Navigation("Challenges");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Portal.Models.User", b =>
                {
                    b.Navigation("CreatedChallenges");

                    b.Navigation("Enrollments");

                    b.Navigation("Scenarios");

                    b.Navigation("TaughtClasses");
                });

            modelBuilder.Entity("Portal.Models.UserStatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
